# Generated by Django 3.1 on 2020-08-16 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование группы')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование монеты')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('img', models.ImageField(upload_to='', verbose_name='Фото')),
                ('year', models.IntegerField(verbose_name='Год выпуска')),
                ('denomination', models.CharField(max_length=255, verbose_name='Номинал')),
                ('diameter', models.PositiveIntegerField(verbose_name='Диаметр')),
                ('edition', models.PositiveIntegerField(verbose_name='Тираж')),
                ('material', models.CharField(max_length=255, verbose_name='Материал')),
                ('weight', models.PositiveIntegerField(verbose_name='Вес')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.group')),
            ],
            options={
                'verbose_name': 'Монета',
                'verbose_name_plural': 'Монеты',
            },
        ),
    ]
