# Generated by Django 3.0.8 on 2020-08-29 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование группы')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование монеты')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Цена')),
                ('img', models.ImageField(blank=True, null=True, upload_to='collection/photo/%Y/%m/%d/', verbose_name='Фото')),
                ('year', models.CharField(blank=True, max_length=255, null=True, verbose_name='Год выпуска')),
                ('denomination', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номинал')),
                ('diameter', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Диаметр')),
                ('edition', models.IntegerField(blank=True, null=True, verbose_name='Тираж')),
                ('material', models.CharField(blank=True, max_length=255, null=True, verbose_name='Материал')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Вес')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.Group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Монета',
                'verbose_name_plural': 'Монеты',
            },
        ),
    ]
