# Generated by Django 3.1 on 2020-08-16 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='denomination',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Номинал'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='diameter',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Диаметр'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='edition',
            field=models.IntegerField(blank=True, verbose_name='Тираж'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.group', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='img',
            field=models.ImageField(upload_to='collection/photo/%Y/%m/%d/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='material',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Вес'),
        ),
    ]
