# Generated by Django 3.1 on 2020-08-16 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_auto_20200816_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='diameter',
            field=models.IntegerField(blank=True, null=True, verbose_name='Диаметр'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='year',
            field=models.CharField(max_length=255, verbose_name='Год выпуска'),
        ),
    ]
